name = "chilfish-top"
compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2024-09-23"

# [vars]
# MY_VAR = "my-variable"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
